/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AAdditionalExpression extends PAdditionalExpression
{
    private TComa _coma_;
    private PExpression _expression_;

    public AAdditionalExpression()
    {
    }

    public AAdditionalExpression(
        TComa _coma_,
        PExpression _expression_)
    {
        setComa(_coma_);

        setExpression(_expression_);

    }
    public Object clone()
    {
        return new AAdditionalExpression(
            (TComa) cloneNode(_coma_),
            (PExpression) cloneNode(_expression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAdditionalExpression(this);
    }

    public TComa getComa()
    {
        return _coma_;
    }

    public void setComa(TComa node)
    {
        if(_coma_ != null)
        {
            _coma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _coma_ = node;
    }

    public PExpression getExpression()
    {
        return _expression_;
    }

    public void setExpression(PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expression_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_coma_)
            + toString(_expression_);
    }

    void removeChild(Node child)
    {
        if(_coma_ == child)
        {
            _coma_ = null;
            return;
        }

        if(_expression_ == child)
        {
            _expression_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_coma_ == oldChild)
        {
            setComa((TComa) newChild);
            return;
        }

        if(_expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

    }
}
