/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.parser;

import minipython.node.*;
import minipython.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTTab(TTab node)
    {
        index = 0;
    }

    public void caseTAnd(TAnd node)
    {
        index = 1;
    }

    public void caseTOr(TOr node)
    {
        index = 2;
    }

    public void caseTNot(TNot node)
    {
        index = 3;
    }

    public void caseTColon(TColon node)
    {
        index = 4;
    }

    public void caseTComa(TComa node)
    {
        index = 5;
    }

    public void caseTDot(TDot node)
    {
        index = 6;
    }

    public void caseTAssign(TAssign node)
    {
        index = 7;
    }

    public void caseTLeftParenthesis(TLeftParenthesis node)
    {
        index = 8;
    }

    public void caseTRightParenthesis(TRightParenthesis node)
    {
        index = 9;
    }

    public void caseTLeftBracket(TLeftBracket node)
    {
        index = 10;
    }

    public void caseTRightBracket(TRightBracket node)
    {
        index = 11;
    }

    public void caseTGreaterThan(TGreaterThan node)
    {
        index = 12;
    }

    public void caseTLessEqual(TLessEqual node)
    {
        index = 13;
    }

    public void caseTGreaterEqual(TGreaterEqual node)
    {
        index = 14;
    }

    public void caseTEqual(TEqual node)
    {
        index = 15;
    }

    public void caseTNotEqual(TNotEqual node)
    {
        index = 16;
    }

    public void caseTLessThan(TLessThan node)
    {
        index = 17;
    }

    public void caseTPlus(TPlus node)
    {
        index = 18;
    }

    public void caseTMinus(TMinus node)
    {
        index = 19;
    }

    public void caseTTimes(TTimes node)
    {
        index = 20;
    }

    public void caseTDivide(TDivide node)
    {
        index = 21;
    }

    public void caseTModulo(TModulo node)
    {
        index = 22;
    }

    public void caseTPower(TPower node)
    {
        index = 23;
    }

    public void caseTMinusEqual(TMinusEqual node)
    {
        index = 24;
    }

    public void caseTDivideEqual(TDivideEqual node)
    {
        index = 25;
    }

    public void caseTPlusEqual(TPlusEqual node)
    {
        index = 26;
    }

    public void caseTMultEqual(TMultEqual node)
    {
        index = 27;
    }

    public void caseTTrue(TTrue node)
    {
        index = 28;
    }

    public void caseTFalse(TFalse node)
    {
        index = 29;
    }

    public void caseTNone(TNone node)
    {
        index = 30;
    }

    public void caseTIf(TIf node)
    {
        index = 31;
    }

    public void caseTElse(TElse node)
    {
        index = 32;
    }

    public void caseTWhile(TWhile node)
    {
        index = 33;
    }

    public void caseTFor(TFor node)
    {
        index = 34;
    }

    public void caseTDef(TDef node)
    {
        index = 35;
    }

    public void caseTReturn(TReturn node)
    {
        index = 36;
    }

    public void caseTPrint(TPrint node)
    {
        index = 37;
    }

    public void caseTIn(TIn node)
    {
        index = 38;
    }

    public void caseTAssert(TAssert node)
    {
        index = 39;
    }

    public void caseTLen(TLen node)
    {
        index = 40;
    }

    public void caseTAscii(TAscii node)
    {
        index = 41;
    }

    public void caseTMax(TMax node)
    {
        index = 42;
    }

    public void caseTMin(TMin node)
    {
        index = 43;
    }

    public void caseTTkImport(TTkImport node)
    {
        index = 44;
    }

    public void caseTAs(TAs node)
    {
        index = 45;
    }

    public void caseTFrom(TFrom node)
    {
        index = 46;
    }

    public void caseTId(TId node)
    {
        index = 47;
    }

    public void caseTNum(TNum node)
    {
        index = 48;
    }

    public void caseTDoubleQuote(TDoubleQuote node)
    {
        index = 49;
    }

    public void caseTSingleQuote(TSingleQuote node)
    {
        index = 50;
    }

    public void caseTStringLiteralD(TStringLiteralD node)
    {
        index = 51;
    }

    public void caseTStringLiteralS(TStringLiteralS node)
    {
        index = 52;
    }

    public void caseEOF(EOF node)
    {
        index = 53;
    }
}
